### ISSUE TITLE
In your readme the example command output name is an rpx file, when it should be an elf file, because you recompress it later

### ISSUE THREAD

**Issue by Common-Leap** [mkwcat/gecko-codes#3]
Look up

**Comment by Common-Leap** [comment]
simple mistake, no biggy

**Comment by mkwcat** [comment]
RPX and ELF are the same thing

**Comment by Common-Leap** [comment]
what

**Comment by Common-Leap** [comment]
the script needs an elf file

**Comment by Common-Leap** [comment]
and It outputs one, right? so you need to recompress it

**Comment by mkwcat** [comment]
i don't think you need to recompress it, at least it worked on Cemu without it

**Comment by Common-Leap** [comment]
Oh ok, I assumed you had to, sorry to bother
